from org.Babylonjs.utils import BABYLON, _js_class, _js_math_class

"""autogenerated wrapper stubs for Babylonjs src module"""

# from math2D.ts
Vector2WithInfo = _js_class(BABYLON.GUI.Vector2WithInfo)
Matrix2D = _js_math_class(BABYLON.GUI.Matrix2D)

# from valueAndUnit.ts
ValueAndUnit = _js_class(BABYLON.GUI.ValueAndUnit)

# from measure.ts
Measure = _js_class(BABYLON.GUI.Measure)

# from advancedDynamicTexture.ts
AdvancedDynamicTexture = _js_class(BABYLON.GUI.AdvancedDynamicTexture)

# convenience alias
GUITexture = AdvancedDynamicTexture
