from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs postProcess module"""

# from babylon.refractionPostProcess.ts
RefractionPostProcess = _js_class(BABYLON.RefractionPostProcess)

# from babylon.tonemapPostProcess.ts
TonemapPostProcess = _js_class(BABYLON.TonemapPostProcess)

# from babylon.anaglyphPostProcess.ts
AnaglyphPostProcess = _js_class(BABYLON.AnaglyphPostProcess)

# from babylon.convolutionPostProcess.ts
ConvolutionPostProcess = _js_class(BABYLON.ConvolutionPostProcess)

# from babylon.volumetricLightScatteringPostProcess.ts
VolumetricLightScatteringPostProcess = _js_class(BABYLON.VolumetricLightScatteringPostProcess)

# from babylon.blackAndWhitePostProcess.ts
BlackAndWhitePostProcess = _js_class(BABYLON.BlackAndWhitePostProcess)

# from babylon.highlightsPostProcess.ts
HighlightsPostProcess = _js_class(BABYLON.HighlightsPostProcess)

# from babylon.postProcessManager.ts
PostProcessManager = _js_class(BABYLON.PostProcessManager)

# from babylon.fxaaPostProcess.ts
FxaaPostProcess = _js_class(BABYLON.FxaaPostProcess)

# from babylon.passPostProcess.ts
PassPostProcess = _js_class(BABYLON.PassPostProcess)

# from babylon.filterPostProcess.ts
FilterPostProcess = _js_class(BABYLON.FilterPostProcess)

# from babylon.vrDistortionCorrectionPostProcess.ts
VRDistortionCorrectionPostProcess = _js_class(BABYLON.VRDistortionCorrectionPostProcess)

# from babylon.stereoscopicInterlacePostProcess.ts
StereoscopicInterlacePostProcess = _js_class(BABYLON.StereoscopicInterlacePostProcess)

# from babylon.blurPostProcess.ts
BlurPostProcess = _js_class(BABYLON.BlurPostProcess)

# from babylon.colorCorrectionPostProcess.ts
ColorCorrectionPostProcess = _js_class(BABYLON.ColorCorrectionPostProcess)

# from babylon.imageProcessingPostProcess.ts
ImageProcessingPostProcess = _js_class(BABYLON.ImageProcessingPostProcess)

# from babylon.postProcess.ts
PostProcess = _js_class(BABYLON.PostProcess)

# from babylon.displayPassPostProcess.ts
DisplayPassPostProcess = _js_class(BABYLON.DisplayPassPostProcess)
