from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs PBR module"""

# from babylon.pbrBaseSimpleMaterial.ts

# from babylon.pbrMaterial.ts
PBRMaterial = _js_class(BABYLON.PBRMaterial)

# from babylon.pbrMetallicRoughnessMaterial.ts
PBRMetallicRoughnessMaterial = _js_class(BABYLON.PBRMetallicRoughnessMaterial)

# from babylon.pbrBaseMaterial.ts

# from babylon.pbrSpecularGlossinessMaterial.ts
PBRSpecularGlossinessMaterial = _js_class(BABYLON.PBRSpecularGlossinessMaterial)
