from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs shadows module"""

# from babylon.shadowGenerator.ts
ShadowGenerator = _js_class(BABYLON.ShadowGenerator)
