from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs particles module"""

# from babylon.solidParticleSystem.ts
SolidParticleSystem = _js_class(BABYLON.SolidParticleSystem)

# from babylon.gpuParticleSystem.ts
GPUParticleSystem = _js_class(BABYLON.GPUParticleSystem)

# from babylon.particle.ts
Particle = _js_class(BABYLON.Particle)

# from babylon.particleSystem.ts
ParticleSystem = _js_class(BABYLON.ParticleSystem)

# from babylon.solidParticle.ts
SolidParticle = _js_class(BABYLON.SolidParticle)
ModelShape = _js_class(BABYLON.ModelShape)
DepthSortedParticle = _js_class(BABYLON.DepthSortedParticle)
