from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs VR module"""

# from babylon.vrDeviceOrientationCamera.ts
VRDeviceOrientationFreeCamera = _js_class(BABYLON.VRDeviceOrientationFreeCamera)
VRDeviceOrientationGamepadCamera = _js_class(BABYLON.VRDeviceOrientationGamepadCamera)
VRDeviceOrientationArcRotateCamera = _js_class(BABYLON.VRDeviceOrientationArcRotateCamera)

# from babylon.vrCameraMetrics.ts
VRCameraMetrics = _js_class(BABYLON.VRCameraMetrics)

# from babylon.webVRCamera.ts
WebVRFreeCamera = _js_class(BABYLON.WebVRFreeCamera)

# from babylon.vrExperienceHelper.ts
VRExperienceHelper = _js_class(BABYLON.VRExperienceHelper)
