from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs culling module"""

# from babylon.ray.ts
Ray = _js_class(BABYLON.Ray)

# from babylon.boundingSphere.ts
BoundingSphere = _js_class(BABYLON.BoundingSphere)

# from babylon.boundingInfo.ts
BoundingInfo = _js_class(BABYLON.BoundingInfo)

# from babylon.boundingBox.ts
BoundingBox = _js_class(BABYLON.BoundingBox)
