from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs controllers module"""

# from babylon.genericController.ts
GenericController = _js_class(BABYLON.GenericController)

# from babylon.webVRController.ts

# from babylon.windowsMotionController.ts
WindowsMotionController = _js_class(BABYLON.WindowsMotionController)

# from babylon.oculusTouchController.ts
OculusTouchController = _js_class(BABYLON.OculusTouchController)

# from babylon.poseEnabledController.ts
PoseEnabledControllerHelper = _js_class(BABYLON.PoseEnabledControllerHelper)
PoseEnabledController = _js_class(BABYLON.PoseEnabledController)

# from babylon.viveController.ts
ViveController = _js_class(BABYLON.ViveController)
