from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs events module"""

# from babylon.keyboardEvents.ts
KeyboardEventTypes = _js_class(BABYLON.KeyboardEventTypes)
KeyboardInfo = _js_class(BABYLON.KeyboardInfo)
KeyboardInfoPre = _js_class(BABYLON.KeyboardInfoPre)

# from babylon.pointerEvents.ts
PointerEventTypes = _js_class(BABYLON.PointerEventTypes)
PointerInfoBase = _js_class(BABYLON.PointerInfoBase)
PointerInfoPre = _js_class(BABYLON.PointerInfoPre)
PointerInfo = _js_class(BABYLON.PointerInfo)
