from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs lights module"""

# from babylon.hemisphericLight.ts
HemisphericLight = _js_class(BABYLON.HemisphericLight)

# from babylon.spotLight.ts
SpotLight = _js_class(BABYLON.SpotLight)

# from babylon.directionalLight.ts
DirectionalLight = _js_class(BABYLON.DirectionalLight)

# from babylon.shadowLight.ts

# from babylon.light.ts
Light = _js_class(BABYLON.Light)

# from babylon.pointLight.ts
PointLight = _js_class(BABYLON.PointLight)
