from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs mesh module"""

# from babylon.groundMesh.ts
GroundMesh = _js_class(BABYLON.GroundMesh)

# from babylon.mesh.ts
_InstancesBatch = _js_class(BABYLON._InstancesBatch)
Mesh = _js_class(BABYLON.Mesh)

# from babylon.geometry.ts
Geometry = _js_class(BABYLON.Geometry)
# Ribbon = _js_class(BABYLON.Ribbon)
# Box = _js_class(BABYLON.Box)
# Sphere = _js_class(BABYLON.Sphere)
# Disc = _js_class(BABYLON.Disc)
# Cylinder = _js_class(BABYLON.Cylinder)
# Torus = _js_class(BABYLON.Torus)
# Ground = _js_class(BABYLON.Ground)
# TiledGround = _js_class(BABYLON.TiledGround)
# Plane = _js_class(BABYLON.Plane)
# TorusKnot = _js_class(BABYLON.TorusKnot)

# from babylon.linesMesh.ts
LinesMesh = _js_class(BABYLON.LinesMesh)

# from babylon.mesh.vertexData.ts
VertexData = _js_class(BABYLON.VertexData)

# from babylon.meshBuilder.ts
MeshBuilder = _js_class(BABYLON.MeshBuilder)

# from babylon.transformNode.ts
TransformNode = _js_class(BABYLON.TransformNode)

# from babylon.meshSimplification.ts
SimplificationSettings = _js_class(BABYLON.SimplificationSettings)
SimplificationQueue = _js_class(BABYLON.SimplificationQueue)
DecimationTriangle = _js_class(BABYLON.DecimationTriangle)
DecimationVertex = _js_class(BABYLON.DecimationVertex)
QuadraticMatrix = _js_class(BABYLON.QuadraticMatrix)
Reference = _js_class(BABYLON.Reference)
QuadraticErrorSimplification = _js_class(BABYLON.QuadraticErrorSimplification)

# from babylon.abstractMesh.ts
AbstractMesh = _js_class(BABYLON.AbstractMesh)

# from babylon.instancedMesh.ts
InstancedMesh = _js_class(BABYLON.InstancedMesh)

# from babylon.csg.ts
CSG = _js_class(BABYLON.CSG)

# from babylon.polygonMesh.ts
Polygon = _js_class(BABYLON.Polygon)
PolygonMeshBuilder = _js_class(BABYLON.PolygonMeshBuilder)

# from babylon.buffer.ts
Buffer = _js_class(BABYLON.Buffer)

# from babylon.vertexBuffer.ts
VertexBuffer = _js_class(BABYLON.VertexBuffer)

# from babylon.meshLODLevel.ts
#MeshLODLevel = _js_class(BABYLON.MeshLODLevel)

# from babylon.subMesh.ts
BaseSubMesh = _js_class(BABYLON.BaseSubMesh)
SubMesh = _js_class(BABYLON.SubMesh)
