from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs states module"""

# from babylon.stencilState.ts
_StencilState = _js_class(BABYLON._StencilState)

# from babylon.depthCullingState.ts
_DepthCullingState = _js_class(BABYLON._DepthCullingState)

# from babylon.alphaCullingState.ts
_AlphaState = _js_class(BABYLON._AlphaState)
