from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs pipelines module"""

# from babylon.defaultRenderingPipeline.ts
DefaultRenderingPipeline = _js_class(BABYLON.DefaultRenderingPipeline)

# from babylon.standardRenderingPipeline.ts
StandardRenderingPipeline = _js_class(BABYLON.StandardRenderingPipeline)

# from babylon.lensRenderingPipeline.ts
LensRenderingPipeline = _js_class(BABYLON.LensRenderingPipeline)

# from babylon.ssaoRenderingPipeline.ts
SSAORenderingPipeline = _js_class(BABYLON.SSAORenderingPipeline)

# from babylon.ssao2RenderingPipeline.ts
SSAO2RenderingPipeline = _js_class(BABYLON.SSAO2RenderingPipeline)
