from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs debug module"""

# from babylon.physicsViewer.ts
PhysicsViewer = _js_class(BABYLON.PhysicsViewer)

# from babylon.debugLayer.ts
DebugLayer = _js_class(BABYLON.DebugLayer)

# from babylon.skeletonViewer.ts
SkeletonViewer = _js_class(BABYLON.SkeletonViewer)

# from babylon.rayHelper.ts
RayHelper = _js_class(BABYLON.RayHelper)

# from babylon.boneAxesViewer.ts
BoneAxesViewer = _js_class(BABYLON.BoneAxesViewer)

# from babylon.axesViewer.ts
AxesViewer = _js_class(BABYLON.AxesViewer)
