from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs HDR module"""

# from babylon.panoramaToCubemap.ts
PanoramaToCubeMapTools = _js_class(BABYLON.PanoramaToCubeMapTools)

# from babylon.hdr.ts
HDRTools = _js_class(BABYLON.HDRTools)

# from babylon.cubemapToSphericalPolynomial.ts
CubeMapToSphericalPolynomialTools = _js_class(BABYLON.CubeMapToSphericalPolynomialTools)
