from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs loading module"""

# from babylon.loadingScreen.ts
DefaultLoadingScreen = _js_class(BABYLON.DefaultLoadingScreen)

# from babylon.sceneLoader.ts
SceneLoader = _js_class(BABYLON.SceneLoader)
