from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs octrees module"""

# from babylon.octree.ts
Octree = _js_class(BABYLON.Octree)

# from babylon.octreeBlock.ts
OctreeBlock = _js_class(BABYLON.OctreeBlock)
