from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs plugins module"""

# from babylon.cannonJSPlugin.ts
CannonJSPlugin = _js_class(BABYLON.CannonJSPlugin)

# from babylon.oimoJSPlugin.ts
OimoJSPlugin = _js_class(BABYLON.OimoJSPlugin)
