from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs rendering module"""

# from babylon.depthRenderer.ts
DepthRenderer = _js_class(BABYLON.DepthRenderer)

# from babylon.renderingGroup.ts
RenderingGroup = _js_class(BABYLON.RenderingGroup)

# from babylon.renderingManager.ts
RenderingManager = _js_class(BABYLON.RenderingManager)

# from babylon.outlineRenderer.ts
OutlineRenderer = _js_class(BABYLON.OutlineRenderer)

# from babylon.boundingBoxRenderer.ts
BoundingBoxRenderer = _js_class(BABYLON.BoundingBoxRenderer)

# from babylon.edgesRenderer.ts
EdgesRenderer = _js_class(BABYLON.EdgesRenderer)

# from babylon.geometryBufferRenderer.ts
GeometryBufferRenderer = _js_class(BABYLON.GeometryBufferRenderer)
