from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs cameras module"""

# from babylon.autoRotationBehavior.ts
AutoRotationBehavior = _js_class(BABYLON.AutoRotationBehavior)

# from babylon.framingBehavior.ts
FramingBehavior = _js_class(BABYLON.FramingBehavior)

# from babylon.bouncingBehavior.ts
BouncingBehavior = _js_class(BABYLON.BouncingBehavior)
