from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs procedurals module"""

# from babylon.proceduralTexture.ts
ProceduralTexture = _js_class(BABYLON.ProceduralTexture)

# from babylon.customProceduralTexture.ts
CustomProceduralTexture = _js_class(BABYLON.CustomProceduralTexture)
