from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs bones module"""

# from babylon.boneLookController.ts
BoneLookController = _js_class(BABYLON.BoneLookController)

# from babylon.bone.ts
Bone = _js_class(BABYLON.Bone)

# from babylon.skeleton.ts
Skeleton = _js_class(BABYLON.Skeleton)

# from babylon.boneIKController.ts
BoneIKController = _js_class(BABYLON.BoneIKController)
