from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs lensFlare module"""

# from babylon.lensFlare.ts
LensFlare = _js_class(BABYLON.LensFlare)

# from babylon.lensFlareSystem.ts
LensFlareSystem = _js_class(BABYLON.LensFlareSystem)
