from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs background module"""

# from babylon.backgroundMaterial.ts
BackgroundMaterial = _js_class(BABYLON.BackgroundMaterial)
