from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs inputs module"""

# from babylon.freeCameraKeyboardMoveInput.ts
FreeCameraKeyboardMoveInput = _js_class(BABYLON.FreeCameraKeyboardMoveInput)

# from babylon.freeCameraDeviceOrientationInput.ts
FreeCameraDeviceOrientationInput = _js_class(BABYLON.FreeCameraDeviceOrientationInput)

# from babylon.arcRotateCameraMouseWheelInput.ts
ArcRotateCameraMouseWheelInput = _js_class(BABYLON.ArcRotateCameraMouseWheelInput)

# from babylon.freeCameraVirtualJoystickInput.ts
FreeCameraVirtualJoystickInput = _js_class(BABYLON.FreeCameraVirtualJoystickInput)

# from babylon.freeCameraTouchInput.ts
FreeCameraTouchInput = _js_class(BABYLON.FreeCameraTouchInput)

# from babylon.freeCameraMouseInput.ts
FreeCameraMouseInput = _js_class(BABYLON.FreeCameraMouseInput)

# from babylon.freeCameraGamepadInput.ts
FreeCameraGamepadInput = _js_class(BABYLON.FreeCameraGamepadInput)

# from babylon.arcRotateCameraVRDeviceOrientationInput.ts
ArcRotateCameraVRDeviceOrientationInput = _js_class(BABYLON.ArcRotateCameraVRDeviceOrientationInput)

# from babylon.arcRotateCameraGamepadInput.ts
ArcRotateCameraGamepadInput = _js_class(BABYLON.ArcRotateCameraGamepadInput)

# from babylon.arcRotateCameraKeyboardMoveInput.ts
ArcRotateCameraKeyboardMoveInput = _js_class(BABYLON.ArcRotateCameraKeyboardMoveInput)

# from babylon.arcRotateCameraPointersInput.ts
ArcRotateCameraPointersInput = _js_class(BABYLON.ArcRotateCameraPointersInput)
