from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs cameras module"""

# from babylon.universalCamera.ts
UniversalCamera = _js_class(BABYLON.UniversalCamera)

# from babylon.virtualJoysticksCamera.ts
VirtualJoysticksCamera = _js_class(BABYLON.VirtualJoysticksCamera)

# from babylon.camera.ts
Camera = _js_class(BABYLON.Camera)

# from babylon.stereoscopicCameras.ts
AnaglyphFreeCamera = _js_class(BABYLON.AnaglyphFreeCamera)
AnaglyphArcRotateCamera = _js_class(BABYLON.AnaglyphArcRotateCamera)
AnaglyphGamepadCamera = _js_class(BABYLON.AnaglyphGamepadCamera)
AnaglyphUniversalCamera = _js_class(BABYLON.AnaglyphUniversalCamera)
StereoscopicFreeCamera = _js_class(BABYLON.StereoscopicFreeCamera)
StereoscopicArcRotateCamera = _js_class(BABYLON.StereoscopicArcRotateCamera)
StereoscopicGamepadCamera = _js_class(BABYLON.StereoscopicGamepadCamera)
StereoscopicUniversalCamera = _js_class(BABYLON.StereoscopicUniversalCamera)

# from babylon.freeCamera.ts
FreeCamera = _js_class(BABYLON.FreeCamera)

# from babylon.deviceOrientationCamera.ts
DeviceOrientationCamera = _js_class(BABYLON.DeviceOrientationCamera)

# from babylon.arcRotateCamera.ts
ArcRotateCamera = _js_class(BABYLON.ArcRotateCamera)

# from babylon.gamepadCamera.ts
GamepadCamera = _js_class(BABYLON.GamepadCamera)

# from babylon.arcRotateCameraInputsManager.ts
ArcRotateCameraInputsManager = _js_class(BABYLON.ArcRotateCameraInputsManager)

# from babylon.touchCamera.ts
TouchCamera = _js_class(BABYLON.TouchCamera)

# from babylon.targetCamera.ts
TargetCamera = _js_class(BABYLON.TargetCamera)

# from babylon.cameraInputsManager.ts
CameraInputsManager = _js_class(BABYLON.CameraInputsManager)

# from babylon.followCamera.ts
FollowCamera = _js_class(BABYLON.FollowCamera)
ArcFollowCamera = _js_class(BABYLON.ArcFollowCamera)

# from babylon.freeCameraInputsManager.ts
FreeCameraInputsManager = _js_class(BABYLON.FreeCameraInputsManager)
