from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs materials module"""

# from babylon.material.ts
MaterialDefines = _js_class(BABYLON.MaterialDefines)
Material = _js_class(BABYLON.Material)

# from babylon.effect.ts
EffectFallbacks = _js_class(BABYLON.EffectFallbacks)
EffectCreationOptions = _js_class(BABYLON.EffectCreationOptions)
Effect = _js_class(BABYLON.Effect)

# from babylon.materialHelper.ts
MaterialHelper = _js_class(BABYLON.MaterialHelper)

# from babylon.standardMaterial.ts
StandardMaterialDefines = _js_class(BABYLON.StandardMaterialDefines)
StandardMaterial = _js_class(BABYLON.StandardMaterial)

# from babylon.multiMaterial.ts
MultiMaterial = _js_class(BABYLON.MultiMaterial)

# from babylon.uniformBuffer.ts
UniformBuffer = _js_class(BABYLON.UniformBuffer)

# from babylon.fresnelParameters.ts
FresnelParameters = _js_class(BABYLON.FresnelParameters)

# from babylon.colorCurves.ts
ColorCurves = _js_class(BABYLON.ColorCurves)

# from babylon.shaderMaterial.ts
ShaderMaterial = _js_class(BABYLON.ShaderMaterial)

# from babylon.imageProcessingConfiguration.ts
ImageProcessingConfiguration = _js_class(BABYLON.ImageProcessingConfiguration)

# from babylon.pushMaterial.ts
PushMaterial = _js_class(BABYLON.PushMaterial)
