from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs animations module"""

# from babylon.easing.ts
EasingFunction = _js_class(BABYLON.EasingFunction)
CircleEase = _js_class(BABYLON.CircleEase)
BackEase = _js_class(BABYLON.BackEase)
BounceEase = _js_class(BABYLON.BounceEase)
CubicEase = _js_class(BABYLON.CubicEase)
ElasticEase = _js_class(BABYLON.ElasticEase)
ExponentialEase = _js_class(BABYLON.ExponentialEase)
PowerEase = _js_class(BABYLON.PowerEase)
QuadraticEase = _js_class(BABYLON.QuadraticEase)
QuarticEase = _js_class(BABYLON.QuarticEase)
QuinticEase = _js_class(BABYLON.QuinticEase)
SineEase = _js_class(BABYLON.SineEase)
BezierCurveEase = _js_class(BABYLON.BezierCurveEase)

# from babylon.runtimeAnimation.ts
RuntimeAnimation = _js_class(BABYLON.RuntimeAnimation)

# from babylon.animation.ts
AnimationRange = _js_class(BABYLON.AnimationRange)
AnimationEvent = _js_class(BABYLON.AnimationEvent)
PathCursor = _js_class(BABYLON.PathCursor)
Animation = _js_class(BABYLON.Animation)

# from babylon.animatable.ts
Animatable = _js_class(BABYLON.Animatable)
