from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs controls module"""

# from rectangle.ts
Rectangle = _js_class(BABYLON.GUI.Rectangle)

# from button.ts
Button = _js_class(BABYLON.GUI.Button)

# from ellipse.ts
Ellipse = _js_class(BABYLON.GUI.Ellipse)

# from radioButton.ts
RadioButton = _js_class(BABYLON.GUI.RadioButton)

# from colorpicker.ts
ColorPicker = _js_class(BABYLON.GUI.ColorPicker)

# from image.ts
Image = _js_class(BABYLON.GUI.Image)

# from control.ts
Control = _js_class(BABYLON.GUI.Control)

# from textBlock.ts
TextBlock = _js_class(BABYLON.GUI.TextBlock)

# from virtualKeyboard.ts
KeyPropertySet = _js_class(BABYLON.GUI.KeyPropertySet)
VirtualKeyboard = _js_class(BABYLON.GUI.VirtualKeyboard)

# from container.ts
Container = _js_class(BABYLON.GUI.Container)

# from checkbox.ts
Checkbox = _js_class(BABYLON.GUI.Checkbox)

# from inputText.ts
InputText = _js_class(BABYLON.GUI.InputText)

# from line.ts
Line = _js_class(BABYLON.GUI.Line)

# from stackPanel.ts
StackPanel = _js_class(BABYLON.GUI.StackPanel)

# from slider.ts
Slider = _js_class(BABYLON.GUI.Slider)
