from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs probes module"""

# from babylon.reflectionProbe.ts
ReflectionProbe = _js_class(BABYLON.ReflectionProbe)
