from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs collisions module"""

# from babylon.pickingInfo.ts
IntersectionInfo = _js_class(BABYLON.IntersectionInfo)
PickingInfo = _js_class(BABYLON.PickingInfo)

# from babylon.collisionCoordinator.ts
CollisionCoordinatorWorker = _js_class(BABYLON.CollisionCoordinatorWorker)
CollisionCoordinatorLegacy = _js_class(BABYLON.CollisionCoordinatorLegacy)

# from babylon.collisionWorker.ts
CollisionCache = _js_class(BABYLON.CollisionCache)
CollideWorker = _js_class(BABYLON.CollideWorker)
CollisionDetectorTransferable = _js_class(BABYLON.CollisionDetectorTransferable)

# from babylon.collider.ts
Collider = _js_class(BABYLON.Collider)
