from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs instrumentation module"""

# from babylon.sceneInstrumentation.ts
SceneInstrumentation = _js_class(BABYLON.SceneInstrumentation)

# from babylon.timeToken.ts
_TimeToken = _js_class(BABYLON._TimeToken)

# from babylon.engineInstrumentation.ts
EngineInstrumentation = _js_class(BABYLON.EngineInstrumentation)
