from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs audio module"""

# from babylon.audioEngine.ts
AudioEngine = _js_class(BABYLON.AudioEngine)

# from babylon.sound.ts
Sound = _js_class(BABYLON.Sound)

# from babylon.analyser.ts
Analyser = _js_class(BABYLON.Analyser)

# from babylon.soundtrack.ts
SoundTrack = _js_class(BABYLON.SoundTrack)
