from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs engine module"""

# from babylon.webgl2.ts

# from babylon.nullEngine.ts
NullEngineOptions = _js_class(BABYLON.NullEngineOptions)
NullEngine = _js_class(BABYLON.NullEngine)

# from babylon.engine.ts
InstancingAttributeInfo = _js_class(BABYLON.InstancingAttributeInfo)
RenderTargetCreationOptions = _js_class(BABYLON.RenderTargetCreationOptions)
EngineCapabilities = _js_class(BABYLON.EngineCapabilities)
Engine = _js_class(BABYLON.Engine)
