from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs helpers module"""

# from babylon.environmentHelper.ts
EnvironmentHelper = _js_class(BABYLON.EnvironmentHelper)
