from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs layer module"""

# from babylon.highlightlayer.ts
HighlightLayer = _js_class(BABYLON.HighlightLayer)

# from babylon.layer.ts
Layer = _js_class(BABYLON.Layer)
