from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs morph module"""

# from babylon.morphTargetManager.ts
MorphTargetManager = _js_class(BABYLON.MorphTargetManager)

# from babylon.morphTarget.ts
MorphTarget = _js_class(BABYLON.MorphTarget)
