from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs tools module"""

# from babylon.andOrNotEvaluator.ts
AndOrNotEvaluator = _js_class(BABYLON.AndOrNotEvaluator)

# from babylon.earcut.ts

# from babylon.sceneOptimizer.ts
SceneOptimization = _js_class(BABYLON.SceneOptimization)
TextureOptimization = _js_class(BABYLON.TextureOptimization)
HardwareScalingOptimization = _js_class(BABYLON.HardwareScalingOptimization)
ShadowsOptimization = _js_class(BABYLON.ShadowsOptimization)
PostProcessesOptimization = _js_class(BABYLON.PostProcessesOptimization)
LensFlaresOptimization = _js_class(BABYLON.LensFlaresOptimization)
ParticlesOptimization = _js_class(BABYLON.ParticlesOptimization)
RenderTargetsOptimization = _js_class(BABYLON.RenderTargetsOptimization)
MergeMeshesOptimization = _js_class(BABYLON.MergeMeshesOptimization)
SceneOptimizerOptions = _js_class(BABYLON.SceneOptimizerOptions)
SceneOptimizer = _js_class(BABYLON.SceneOptimizer)

# from babylon.filesInput.ts
FilesInput = _js_class(BABYLON.FilesInput)

# from babylon.stringDictionary.ts
StringDictionary = _js_class(BABYLON.StringDictionary)

# from babylon.virtualJoystick.ts
VirtualJoystick = _js_class(BABYLON.VirtualJoystick)

# from babylon.tga.ts
TGATools = _js_class(BABYLON.TGATools)

# from babylon.textureTools.ts
TextureTools = _js_class(BABYLON.TextureTools)

# from babylon.database.ts
Database = _js_class(BABYLON.Database)

# from babylon.smartArray.ts
SmartArray = _js_class(BABYLON.SmartArray)
SmartArrayNoDuplicate = _js_class(BABYLON.SmartArrayNoDuplicate)

# from babylon.sceneSerializer.ts
SceneSerializer = _js_class(BABYLON.SceneSerializer)

# from babylon.assetsManager.ts
AssetsProgressEvent = _js_class(BABYLON.AssetsProgressEvent)
MeshAssetTask = _js_class(BABYLON.MeshAssetTask)
TextFileAssetTask = _js_class(BABYLON.TextFileAssetTask)
BinaryFileAssetTask = _js_class(BABYLON.BinaryFileAssetTask)
ImageAssetTask = _js_class(BABYLON.ImageAssetTask)
TextureAssetTask = _js_class(BABYLON.TextureAssetTask)
CubeTextureAssetTask = _js_class(BABYLON.CubeTextureAssetTask)
HDRCubeTextureAssetTask = _js_class(BABYLON.HDRCubeTextureAssetTask)
AssetsManager = _js_class(BABYLON.AssetsManager)

# from babylon.decorators.ts
SerializationHelper = _js_class(BABYLON.SerializationHelper)

# from babylon.performanceMonitor.ts
PerformanceMonitor = _js_class(BABYLON.PerformanceMonitor)
RollingAverage = _js_class(BABYLON.RollingAverage)

# from babylon.khronosTextureContainer.ts
KhronosTextureContainer = _js_class(BABYLON.KhronosTextureContainer)

# from babylon.observable.ts
EventState = _js_class(BABYLON.EventState)
Observer = _js_class(BABYLON.Observer)
MultiObserver = _js_class(BABYLON.MultiObserver)
Observable = _js_class(BABYLON.Observable)

# from babylon.tools.ts
Tools = _js_class(BABYLON.Tools)
PerfCounter = _js_class(BABYLON.PerfCounter)
AsyncLoop = _js_class(BABYLON.AsyncLoop)

# from babylon.tags.ts
Tags = _js_class(BABYLON.Tags)

# from babylon.dds.ts
DDSTools = _js_class(BABYLON.DDSTools)
