from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs renderPipeline module"""

# from babylon.postProcessRenderPipelineManager.ts
PostProcessRenderPipelineManager = _js_class(BABYLON.PostProcessRenderPipelineManager)

# from babylon.postProcessRenderPass.ts
PostProcessRenderPass = _js_class(BABYLON.PostProcessRenderPass)

# from babylon.postProcessRenderEffect.ts
PostProcessRenderEffect = _js_class(BABYLON.PostProcessRenderEffect)

# from babylon.postProcessRenderPipeline.ts
PostProcessRenderPipeline = _js_class(BABYLON.PostProcessRenderPipeline)
