from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs gamepad module"""

# from babylon.gamepad.ts
StickValues = _js_class(BABYLON.StickValues)
Gamepad = _js_class(BABYLON.Gamepad)
GenericPad = _js_class(BABYLON.GenericPad)

# from babylon.xboxGamepad.ts
Xbox360Pad = _js_class(BABYLON.Xbox360Pad)

# from babylon.gamepadManager.ts
GamepadManager = _js_class(BABYLON.GamepadManager)
