from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs actions module"""

# from babylon.condition.ts
Condition = _js_class(BABYLON.Condition)
ValueCondition = _js_class(BABYLON.ValueCondition)
PredicateCondition = _js_class(BABYLON.PredicateCondition)
StateCondition = _js_class(BABYLON.StateCondition)

# from babylon.actionManager.ts
ActionEvent = _js_class(BABYLON.ActionEvent)
ActionManager = _js_class(BABYLON.ActionManager)

# from babylon.interpolateValueAction.ts
InterpolateValueAction = _js_class(BABYLON.InterpolateValueAction)

# from babylon.directActions.ts
SwitchBooleanAction = _js_class(BABYLON.SwitchBooleanAction)
SetStateAction = _js_class(BABYLON.SetStateAction)
SetValueAction = _js_class(BABYLON.SetValueAction)
IncrementValueAction = _js_class(BABYLON.IncrementValueAction)
PlayAnimationAction = _js_class(BABYLON.PlayAnimationAction)
StopAnimationAction = _js_class(BABYLON.StopAnimationAction)
DoNothingAction = _js_class(BABYLON.DoNothingAction)
CombineAction = _js_class(BABYLON.CombineAction)
ExecuteCodeAction = _js_class(BABYLON.ExecuteCodeAction)
SetParentAction = _js_class(BABYLON.SetParentAction)
PlaySoundAction = _js_class(BABYLON.PlaySoundAction)
StopSoundAction = _js_class(BABYLON.StopSoundAction)

# from babylon.action.ts
Action = _js_class(BABYLON.Action)
