from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs physics module"""

# from babylon.physicsImpostor.ts
PhysicsImpostor = _js_class(BABYLON.PhysicsImpostor)

# from babylon.physicsEngine.ts
PhysicsEngine = _js_class(BABYLON.PhysicsEngine)

# from babylon.physicsJoint.ts
PhysicsJoint = _js_class(BABYLON.PhysicsJoint)
DistanceJoint = _js_class(BABYLON.DistanceJoint)
MotorEnabledJoint = _js_class(BABYLON.MotorEnabledJoint)
HingeJoint = _js_class(BABYLON.HingeJoint)
Hinge2Joint = _js_class(BABYLON.Hinge2Joint)

# from babylon.physicsHelper.ts
PhysicsHelper = _js_class(BABYLON.PhysicsHelper)
PhysicsRadialExplosionEvent = _js_class(BABYLON.PhysicsRadialExplosionEvent)
PhysicsGravitationalFieldEvent = _js_class(BABYLON.PhysicsGravitationalFieldEvent)
PhysicsUpdraftEvent = _js_class(BABYLON.PhysicsUpdraftEvent)
