from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs sprites module"""

# from babylon.spriteManager.ts
SpriteManager = _js_class(BABYLON.SpriteManager)

# from babylon.sprite.ts
Sprite = _js_class(BABYLON.Sprite)
