from org.Babylonjs.utils import BABYLON, _js_class
"""autogenerated wrapper stubs for Babylonjs textures module"""

# from babylon.refractionTexture.ts
RefractionTexture = _js_class(BABYLON.RefractionTexture)

# from babylon.videoTexture.ts
VideoTexture = _js_class(BABYLON.VideoTexture)

# from babylon.rawTexture.ts
RawTexture = _js_class(BABYLON.RawTexture)

# from babylon.texture.ts
Texture = _js_class(BABYLON.Texture)

# from babylon.mirrorTexture.ts
MirrorTexture = _js_class(BABYLON.MirrorTexture)

# from babylon.multiRenderTarget.ts
MultiRenderTarget = _js_class(BABYLON.MultiRenderTarget)

# from babylon.cubeTexture.ts
CubeTexture = _js_class(BABYLON.CubeTexture)

# from babylon.internalTexture.ts
InternalTexture = _js_class(BABYLON.InternalTexture)

# from babylon.renderTargetTexture.ts
RenderTargetTexture = _js_class(BABYLON.RenderTargetTexture)

# from babylon.dynamicTexture.ts
DynamicTexture = _js_class(BABYLON.DynamicTexture)

# from babylon.baseTexture.ts
BaseTexture = _js_class(BABYLON.BaseTexture)

# from babylon.colorGradingTexture.ts
ColorGradingTexture = _js_class(BABYLON.ColorGradingTexture)

# from babylon.hdrCubeTexture.ts
HDRCubeTexture = _js_class(BABYLON.HDRCubeTexture)
